disabled_rules:
- trailing_whitespace
- line_length
- type_name

opt_in_rules:
- empty_count
- empty_string
- overridden_super_call
- private_outlet
- prohibited_super_call
- first_where
- closure_spacing
- unneeded_parentheses_in_closure_argument
- redundant_nil_coalescing
- pattern_matching_keywords
- explicit_init
- contains_over_first_not_nil

excluded:
- Carthage
- Pods
- RxSwift
- RxCocoa
- RxTest
- RxBlocking
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 120
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"
